### ISSUE TITLE
0.04 で 「-lwtmpdir」 オプションを指定しないと aui_indexer が動作しない

### ISSUE THREAD

**Issue by maki-rxrz** [rigaya/aui_indexer#1]
0.04 の新機能「-lwtmpdir」を指定しないで動作させると、aui_indexer.cpp(243) の tmpdir チェックで止まってしまいます。
確認の程、宜しくお願いします。

**Comment by rigaya** [comment]
ご報告ありがとうございます。

なんとも簡単なミスでした…。https://github.com/rigaya/aui_indexer/commit/7d3a3ce39acd0401c5bbc53d29083525d5b22de2 で修正しました。
