### ISSUE TITLE
lwinput.aui の生成するlwiファイルにゴミ(ログ)が混じる問題

### ISSUE THREAD

**Issue by maki-rxrz** [rigaya/aui_indexer#2]
【概要】
lwinput.aui が出力する libavformat/libavcodec のログがlwiファイル上に出力される事がある。(発生率は低
※ 私個人のPC環境では30回に1回くらいの頻度で発生

【原因】
>   aui_indexer.exe:  fclose(stderr);
> 　　　　　　　　　　↓  func_open()
>  lwinput.aui    :  lw_fopen("対象ファイル");   // _wfopen or fopen

の流れにおいて、fcloseで破棄したstderrを示すアドレスが、以降のファイルオープン時のFILE *に割り当てられる事が稀にあり、libavformat/libavcodec のログがlwiファイルへと出力されてしまう現象が発生する。

 [参考例]
以下、同じ入力ファイルでの現象発生時と未発生時のlwiファイルの状態。（ログ出力が混じっている

現象発生時：誤)
>  [AVBSFContext @ 006baa80] Error parsing ADTS frame header!
>  [aac @ 006b56c0] Sample rate index in program config element does not match the sample rate index   configured by the container<ActiveVideoStreamIndex\>+0000000000</ActiveVideoStreamIndex\>
>  <ActiveAudioStreamIndex\>+0000000001</ActiveAudioStreamIndex\>
>  .0>
>  <LibavReaderIndexFile=13\>
>  <InputFilePath\>～～～.ts</InputFilePath\>
>  <LibavReaderIndex=0x00000208,0,mpegts\>
>  <ActiveVideoStreamIndex\>-0000000001</ActiveVideoStreamIndex\>
>  <ActiveAudioStreamIndex\>-0000000001</ActiveAudioStreamIndex\>
> Index=1,Type=1,Codec=86018,TimeBase=1/90000,POS=10716,PTS=286195465,DTS=286195465,EDI=0

未発生時：正)
>  <LSMASHWorksIndexVersion=0.0.2.0\>
>  <LibavReaderIndexFile=13\>
>  <InputFilePath\>～～～.ts</InputFilePath\>
>  <LibavReaderIndex=0x00000208,0,mpegts>
>  <ActiveVideoStreamIndex\>+0000000000</ActiveVideoStreamIndex\>
>  <ActiveAudioStreamIndex\>+0000000001</ActiveAudioStreamIndex\>
> Index=1,Type=1,Codec=86018,TimeBase=1/90000,POS=10716,PTS=286195465,DTS=286195465,EDI=0

【補足】
L-SMASH WorksのLibav Readerはlwiファイルが読み込み不可な場合はlwiファイルを再生成する為、本現象が発生したlwi生成済みファイルを読み込むと再生成完了まで暫く待たされる状況に遭遇する。

これが、本件が発生している事になかなか気づけない要因にもなっている。（再生成でログ混じりlwiが消えてしまうので）

【備考】
エラー出力(stderr)を殺す、以外の手段でログ出力の抑制するには以下のいずれかの手段をとる事。

1. L-SMASH Works内にてログ出力のレベルを設定 (以下を適切なタイミングで呼ぶ、要パッチ当てビルド)
`    av_log_set_level( AV_LOG_QUIET );`

2. aui_indexer.exe の実行時に標準エラー出力をNULへ流す (原因コードを除いてビルドする必要有)
`    aui_indexer.exe -aui lwinput.aui xxx.ts 2>NUL`

又、stderrを殺さずにLibav+L-SMASH(MP4読込)が有効な設定でTSファイル等を読む込むと以下のL-SMASHのログが出力される。(MP4読込を先に試行する為)

`  [importer: Error]: failed to find the matched importer.`

これが表示されるのを抑制したい場合は以下の（略

1. L-SMASH Worksの設定でLibav+L-SMASH(MP4読込)を無効にしておく
2. NULへ流す（上記参照）

※ aui_indexerやL-SMASH Worksを自ビルドできないユーザーは、現状では本件を完全回避する事はできません

**Comment by rigaya** [comment]
ご報告、また問題の原因を分析いただき、ありがとうございました。たしかになかなか気づかないです…。

提示いただいているように、stderrを閉じるのではなくNULへ流すようにしました。手元では100回lwiを作らせると5回ぐらいコミが混ざっていたのが、変更により1回も起こらなくなったので、大丈夫かと思います。

**Comment by maki-rxrz** [comment]
対応ありがとうございます。私の手元でも(ざっとですが)テストし発生しない事を確認しました。
Issueをcloseします。
